from app.dao.base import BaseDAO
from app.dao.user_dao import UserDAO
from app.dao.vehicle_dao import VehicleDAO
from app.dao.order_dao import OrderDAO
from app.dao.detail_dao import DetailDAO
from app.dao.pile_dao import PileDAO
from app.dao.queue_dao import QueueDAO
from app.dao.fault_dao import FaultDAO
from app.dao.report_dao import ReportDAO
